config/routes.rb
Rails.application.routes.draw do
    
  get 'cards/new'
  devise_for :users
  root to: "items#index"
  resources :items do
    resources :purchases, only: [:index,:create]
  end
  resources :users, only: [:show, :edit, :update]
  resources :cards, only: [:new, :create]
end

app/models/user.rb
class User < ApplicationRecord
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :items
  has_many :purchases
  has_one :card, dependent: :destroy

  PASSWORD_REGEX = /\A(?=.*?[a-z])(?=.*?\d)[a-z\d]+\z/i.freeze
  NAME_REGEX = /\A[ぁ-んァ-ヶ一-龥々ー]+\z/.freeze
  KANA_REGEX = /\A[ァ-ヶー]+\z/.freeze

  with_options presence: true do
    validates :nickname
    validates :last_name
    validates :first_name
    validates :read_last_name
    validates :read_first_name
    validates :birthday
  end

  validates :password, format: { with: PASSWORD_REGEX, message: 'は半角英数字の組合せで入力してください' }, if: proc { |user|user.password.present?}

  with_options format: { with: KANA_REGEX, message: 'は全角カタカナで入力してください' } do
    validates :read_last_name, if: proc { |user|user.read_last_name.present?}

    validates :read_first_name, if: proc { |user|user.read_first_name.present?}
  end

  with_options format: { with: NAME_REGEX, message: 'は全角日本語で入力してください' } do
    validates :last_name, if: proc { |user|user.last_name.present?}

    validates :first_name, if: proc { |user|user.first_name.present?}
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :user_find, only: [:edit, :update, :destroy]
  def show
    Payjp.api_key = ENV["PAYJP_SECRET_KEY"]
    card = Card.find_by(user_id: current_user.id)
    if card.present?
      customer = Payjp::Customer.retrieve(card.customer_token)
      @card = customer.cards.first
    end
  end

  def edit
  end

  def update
    if @user.update(user_params)
      redirect_to root_path
    else
      redirect_to action: "edit"
    end
  end
  private

  def user_params
    params.require(:user).permit(:nickname, :email, :last_name, :first_name, :read_last_name, :read_first_name, :birthday)
  end

  def user_find
    @user = User.find(params[:id])
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/edit.html.erb
<%= render "shared/second-header"%>

<%= form_with model: @user, url: user_path(current_user.id), class: 'registration-main', local: true do |f| %>
<div class='form-wrap'>
  <div class='form-header'>
    <h1 class='form-header-text'>
      会員情報編集
    </h1>
  </div>

  <%= render 'shared/error_messages', model: f.object %>

  <div class="form-group">
    <div class='form-text-wrap'>
      <label class="form-text">ニックネーム</label>
      <span class="indispensable">必須</span>
    </div>
    <%= f.text_area :nickname, class:"input-default", id:"nickname", placeholder:"例) furima太郎", maxlength:"40" %>
  </div>
  <div class="form-group">
    <div class='form-text-wrap'>
      <label class="form-text">メールアドレス</label>
      <span class="indispensable">必須</span>
    </div>
    <%= f.email_field :email, class:"input-default", id:"email", placeholder:"PC・携帯どちらでも可", autofocus: true %>
  </div>
  <div class="form-group">
    <div class='form-text-wrap'>
      <label class="form-text">お名前(全角)</label>
      <span class="indispensable">必須</span>
    </div>
    <div class='input-name-wrap'>
      <%= f.text_area :last_name, class:"input-name", id:"last-name", placeholder:"例) 山田" %>
      <%= f.text_area :first_name, class:"input-name", id:"first-name", placeholder:"例) 陸太郎" %>
    </div>
  </div>
  <div class="form-group">
    <div class='form-text-wrap'>
      <label class="form-text">お名前カナ(全角)</label>
      <span class="indispensable">必須</span>
    </div>
    <div class='input-name-wrap'>
      <%= f.text_area :read_last_name, class:"input-name", id:"last-name-kana", placeholder:"例) ヤマダ" %>
      <%= f.text_area :read_first_name, class:"input-name", id:"first-name-kana", placeholder:"例) リクタロウ" %>
    </div>
  </div>
  <div class="form-group">
    <div class='form-text-wrap'>
      <label class="form-text">生年月日</label>
      <span class="indispensable">必須</span>
    </div>
    <div class='input-birth-wrap'>
      <%= raw sprintf(
                  f.date_select(
                    :birthday,
                    class:'select-birth',
                    id:"birth-date",
                    use_month_numbers: true,
                    prompt:'--',
                    start_year: 1930,
                    end_year: (Time.now.year - 5),
                    date_separator: '%s'),
                  "<p> 年 </p>", "<p> 月 </p>") + "<p> 日 </p>" %>
    </div>
  </div>

  <div class='register-btn'>
    <%= f.submit "登録情報変更" ,class:"register-red-btn" %>
  </div>

  <div class='user-btn'>
    <h1 class='user-btn-text'>
      <%=link_to 'もどる', :back, class:"user-back-btn" %> 
    </h1>
  </div>
</div>
<% end %>

<%= render "shared/second-footer"%>

app/views/users/show.html.erb
<%= render "shared/second-header"%>

<div class='transaction-contents'>
  <div class='transaction-main'>
    <table class="detail-table">
      <tbody>
        <div class="Card__title">
          <h1>【ユーザー情報】</h1>
        </div>
        <tr>
          <th class="detail-item">ニックネーム</th>
          <td class="detail-value"><%= current_user.nickname %></td>
        </tr>
        <tr>
          <th class="detail-item">メールアドレス</th>
          <td class="detail-value"><%= current_user.email %></td>
        </tr>
        <tr>
          <th class="detail-item">お名前</th>
          <td class="detail-value"><%= current_user.last_name + "  " + current_user.first_name %></td>
        </tr>
        <tr>
          <th class="detail-item">お名前カナ</th>
          <td class="detail-value"><%= current_user.read_last_name + "  "  + current_user.read_first_name %></td>
        </tr>
        <tr>
          <th class="detail-item">生年月日</th>
          <td class="detail-value"><%= "#{current_user.birthday.year}年#{current_user.birthday.mon}月#{current_user.birthday.mday}日" %></td>
        </tr>
      </tbody>
    </table>
    <div class="user-edit-box">
      <%= link_to "ユーザー情報の編集", edit_user_path, method: :get, class: "user-edit-btn" %>
    </div>

    <% if current_user.card.present?%>
    <table class="detail-table">
      <tbody>
        <div class="Card__title">
          <h1>カード情報</h1>
        </div>
        <tr>
          <th class="detail-item">カード番号</th>
          <td class="detail-value"><%= "**** **** **** " + @card[:last4] %></td>
        </tr>
        <tr>
          <th class="detail-item">有効期限</th>
          <td class="detail-value"><%= @card[:exp_month] %>/<%= @card[:exp_year] %></td>
        </tr>
      </tbody>
    </table>
    <% else %>
      <div class="Card__title">
        <h1>【カード情報が登録されていません】</h1>
      </div>
      <div class="user-edit-box">
      <%= link_to "カード情報登録", new_card_path, method: :get, class: "user-edit-btn" %>
    </div>
    <% end %>
  </div>
</div>

<%= render "shared/second-footer"%>