config/routes.rb
Rails.application.routes.draw do
    
  get 'cards/new'
  devise_for :users
  root to: "items#index"
  resources :items do
    resources :purchases, only: [:index,:create]
  end
  resources :users, only: [:show, :edit, :update]
  resources :cards, only: [:new, :create]
end

app/models/card.rb
class Card < ApplicationRecord
  belongs_to :user
end

app/controllers/cards_controller.rb
class CardsController < ApplicationController
  def new
  end

  def create
    Payjp.api_key = ENV["PAYJP_SECRET_KEY"] 
    redirect_to action: "new" and return if params[:card_token] == nil
    customer = Payjp::Customer.create(
    description: 'test', 
    card: params[:card_token] 
    )
    card = Card.new( 
      card_token: params[:card_token], 
      customer_token: customer.id, 
      user_id: current_user.id 
    )
      if card.save
        redirect_to root_path
      else
        redirect_to action: "new" 
      end
    end
end

app/helpers/cards_helper.rb
module CardsHelper
end

app/views/cards/new.html.erb
<%= render "shared/second-header"%>


  <%= form_with  url: cards_path, id: 'charge-form', class: 'charge-form',local: true do |f| %>
  <div class='form-wrap'>
    <div class='form-header'>
      <div class="Cardpage">
        <h1>カード登録</h1>
      </div><br>
    </div>

    <div class='form-group'>
      <div class='form-text-wrap'>
        <%= f.label :number, "カード番号", class: "form-text" %>
        <span class="indispensable">必須</span>
      </div>
      <%= f.text_field :number, class:"number", placeholder:"カード番号(半角英数字)", maxlength:"16" %>
      <div class='available-card'>
        <%= image_tag 'card-visa.gif', class: 'card-logo'%>
        <%= image_tag 'card-mastercard.gif', class: 'card-logo'%>
        <%= image_tag 'card-jcb.gif', class: 'card-logo'%>
        <%= image_tag 'card-amex.gif', class: 'card-logo'%>
      </div>
    </div>

    <div class='form-group'>
      <div class='form-text-wrap'>
        <label class="form-text">有効期限</label>
        <span class="indispensable">必須</span>
      </div>
      <div class='input-expiration-date-wrap'>
        <%= f.select :exp_month, 1..12, {include_blank: "---"}, class: "exp_month" %>
        <p>月</p>
        <%= f.select :exp_year, 20..25, {include_blank: "---"}, class: "exp_year" %>
        <p>年</p>
      </div>
    </div>

    <div class='form-group'>
      <div class='form-text-wrap'>
        <%= f.label :cvc ,"セキュリティコード", class: "form-text" %>
        <span class="indispensable">必須</span>
      </div>
      <%= f.text_field :cvc, class:"cvc", placeholder:"カード背面にある3桁の番号", maxlength:"4" %>
    </div>

    <div class='register-btn'>
      <br>
      <%= f.submit "登録する" , class:"card-button" %>
    </div>
  </div>
  <% end %>

<%= render "shared/second-footer"%>